---
- name: override dir
  file:
    path: '/etc/systemd/system/getty@.service.d'
    state: 'directory'
    owner: root
    group: root
    mode: 0755
  when:
    - tty_noclear is defined
    - tty_noclear | lower() in [ "true", "yes" ]
  notify: systemd reload
  tags:
    - tty
    - dir

- name: delete old override file
  file:
    path: '/etc/systemd/system/getty@.service.d/noclear.conf'
    state: absent
  when:
    - tty_noclear is defined
    - tty_noclear | lower() in [ "true", "yes" ]
  notify: systemd reload
  tags:
    - tty
    - file

- name: override file
  template:
    src: 'getty.override.conf.j2'
    dest: '/etc/systemd/system/getty@.service.d/override.conf'
    mode: 0644
    owner: root
    group: root
  when:
    - tty_noclear is defined
    - tty_noclear | lower() in [ "true", "yes" ]
  notify: systemd reload
  tags:
    - tty
    - file
...
