---
- name: "getty noclear (dir)"
  file:
    path: '/etc/systemd/system/getty@.service.d'
    state: 'directory'
    owner: root
    group: root
    mode: 0755
  when:
    - tty_noclear is defined
    - tty_noclear | lower() in [ "true", "yes" ]
  notify: systemd reload
  tags:
    - tty
    - dir

- name: "getty noclear (file)"
  template:
    src: 'getty.noclear.conf.j2'
    dest: '/etc/systemd/system/getty@.service.d/noclear.conf'
    mode: 0644
    owner: root
    group: root
  when:
    - tty_noclear is defined
    - tty_noclear | lower() in [ "true", "yes" ]
  notify: systemd reload
  tags:
    - tty
    - file
...
